# Generated by Django 6.0.5 on 2026-05-23 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, unique=True)),
                ('especialidad', models.CharField(choices=[('tren_superior', 'Tren Superior'), ('tren_inferior', 'Tren Inferior'), ('tren_medio', 'Tren Medio')], default='tren_superior', max_length=20)),
                ('tipo_clase', models.CharField(choices=[('fija', 'Fija'), ('individual', 'Individual')], default='fija', max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('dias', models.CharField(default='', max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('ofertada', models.BooleanField(default=False)),
                ('cupo', models.PositiveIntegerField(default=10)),
                ('inscriptos', models.ManyToManyField(blank=True, related_name='clases_inscripto', to=settings.AUTH_USER_MODEL)),
                ('lista_espera', models.ManyToManyField(blank=True, related_name='clases_en_espera', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_como_profesor', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='clases.sala')),
            ],
        ),
    ]
