# Generated by Django 6.0.5 on 2026-05-20 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('dias', models.CharField(max_length=100)),
                ('aula', models.CharField(max_length=50)),
                ('cupo', models.PositiveIntegerField(default=10)),
                ('inscriptos', models.ManyToManyField(blank=True, related_name='clases_inscripto', to=settings.AUTH_USER_MODEL)),
                ('lista_espera', models.ManyToManyField(blank=True, related_name='clases_en_espera', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_como_profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
