# Generated by Django 6.0.5 on 2026-05-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clase',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='tipo',
        ),
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clase',
            name='especialidad',
            field=models.CharField(choices=[('tren_superior', 'Tren Superior'), ('tren_inferior', 'Tren Inferior'), ('tren_medio', 'Tren Medio')], default='tren_superior', max_length=20),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='ofertada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='tipo_clase',
            field=models.CharField(choices=[('fija', 'Fija'), ('individual', 'Individual')], default='fija', max_length=20),
        ),
        migrations.AddField(
            model_name='clase',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clase',
            name='dias',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clase',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='clases.sala'),
        ),
    ]
