# Generated by Django 6.0.5 on 2026-05-26 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('tren_superior', 'Tren Superior'), ('tren_inferior', 'Tren Inferior'), ('tren_medio', 'Tren Medio')], max_length=20)),
                ('turno', models.CharField(blank=True, default='', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
