# Generated by Django 6.0.5 on 2026-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_reserva_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('suscripcion', 'Suscripción'), ('unica', 'Única')], default='unica', max_length=15),
        ),
    ]
