# Generated by Django 6.0.5 on 2026-05-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='clases.clase'),
        ),
    ]
