# Generated by Django 6.0.5 on 2026-05-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_reserva_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('admin', 'Cancelada por administrador'), ('sin_profesor', 'Sin profesor asignado'), ('sin_cuorum', 'Sin cuórum')], max_length=20, null=True),
        ),
    ]
