# Generated by Django 6.0.5 on 2026-05-28 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_clase_estado_clase_fecha_cancelacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='cancelaciones_24_48h',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='descuento_siguiente_mes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_clase', models.CharField(max_length=20)),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
