# Generated by Django 6.0.5 on 2026-06-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_suscripcion_valor_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pendiente_pago', 'Pendiente de pago'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
