# Generated by Django 6.0.5 on 2026-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0008_alter_suscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
