# Generated by Django 6.0.5 on 2026-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0010_add_asistencia_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('falta_de_pago', 'Falta de pago')], max_length=30, null=True),
        ),
    ]
