# Generated by Django 6.0.5 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_address_apt_user_address_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='especialidades',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
